In [3]:
import pandas as pd

eval_df = pd.read_json("../data/processed/eval_v10.jsonl", lines=True)
eval_df.head()

,corrupted,original,verdict,reason
0,Wir geht morgen auf zehn los.,Wir gehen morgen um zehn los.,KEEP,Corrupt sentence is clearly ungrammatical (ver...
1,Wie kann du so ein Mann lieben?,Wie kannst du so einen Mann lieben?,KEEP,Clear grammatical errors (missing verb ending ...
2,Ich kann faulen Menschen nicht aussteht.,Ich kann faule Menschen nicht ausstehen.,KEEP,Clear grammatical errors (incorrect adjective ...
3,Manchmal fühle ich mich wie einen mutterlose K...,Manchmal fühle ich mich wie ein mutterloses Kind.,KEEP,Clear grammatical errors (case and adjective e...
4,Was genau musst er tut?,Was genau muss er tun?,KEEP,Clear subject‑verb agreement and infinitive er...

In [4]:
from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "../models/Ministral-3-3B-Instruct-2512-GEC-v9", # Point directly to the ADAPTER folder
    max_seq_length = 512,          # Use the same as your training
    load_in_4bit = True,            # Set to True if you trained with 4-bit
    dtype = None,                   # Auto-detect (Float16/Bfloat16)
    # device_map="cpu"
)

# Switch model to inference mode (merges LoRA weights for generation)
FastLanguageModel.for_inference(model)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

d:\dev\text-tune-ai\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
W0326 20:24:07.858000 228 Lib\site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.

🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.3.4: Fast Mistral3 patching. Transformers: 5.2.0.
   \\   /|    NVIDIA GeForce RTX 3070 Ti. Num GPUs = 1. Max memory: 8.0 GB. Platform: Windows.
O^O/ \_/ \    Torch: 2.10.0+cu130. CUDA: 8.6. CUDA Toolkit: 13.0. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights: 100%|██████████| 458/458 [00:01<00:00, 342.85it/s, Materializing param=model.vision_tower.transformer.layers.23.ffn_norm.weight]

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): Mistral3ForConditionalGeneration(
      (model): Mistral3Model(
        (vision_tower): PixtralVisionModel(
          (patch_conv): Conv2d(3, 1024, kernel_size=(14, 14), stride=(14, 14), bias=False)
          (ln_pre): PixtralRMSNorm((1024,), eps=1e-05)
          (transformer): PixtralTransformer(
            (layers): ModuleList(
              (0-23): 24 x PixtralAttentionLayer(
                (attention_norm): PixtralRMSNorm((1024,), eps=1e-05)
                (feed_forward): PixtralMLP(
                  (gate_proj): lora.Linear(
                    (base_layer): Linear(in_features=1024, out_features=4096, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Identity()
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=1024, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=4096, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (up_proj): lora.Linear(
                    (base_layer): Linear(in_features=1024, out_features=4096, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Identity()
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=1024, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=4096, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (down_proj): lora.Linear(
                    (base_layer): Linear(in_features=4096, out_features=1024, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Identity()
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=4096, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=1024, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (act_fn): SiLUActivation()
                )
                (attention): PixtralAttention(
                  (k_proj): lora.Linear(
                    (base_layer): Linear(in_features=1024, out_features=1024, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Identity()
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=1024, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=1024, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (v_proj): lora.Linear(
                    (base_layer): Linear(in_features=1024, out_features=1024, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Identity()
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=1024, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=1024, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (q_proj): lora.Linear(
                    (base_layer): Linear(in_features=1024, out_features=1024, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Identity()
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=1024, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=1024, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                  (o_proj): lora.Linear(
                    (base_layer): Linear(in_features=1024, out_features=1024, bias=False)
                    (lora_dropout): ModuleDict(
                      (default): Identity()
                    )
                    (lora_A): ModuleDict(
                      (default): Linear(in_features=1024, out_features=16, bias=False)
                    )
                    (lora_B): ModuleDict(
                      (default): Linear(in_features=16, out_features=1024, bias=False)
                    )
                    (lora_embedding_A): ParameterDict()
                    (lora_embedding_B): ParameterDict()
                    (lora_magnitude_vector): ModuleDict()
                  )
                )
                (ffn_norm): PixtralRMSNorm((1024,), eps=1e-05)
              )
            )
          )
          (patch_positional_embedding): PixtralRotaryEmbedding()
        )
        (multi_modal_projector): Mistral3MultiModalProjector(
          (norm): Mistral3RMSNorm((1024,), eps=1e-05)
          (patch_merger): Mistral3PatchMerger(
            (merging_layer): Linear(in_features=4096, out_features=1024, bias=False)
          )
          (linear_1): Linear(in_features=1024, out_features=3072, bias=False)
          (act): GELUActivation()
          (linear_2): Linear(in_features=3072, out_features=3072, bias=False)
        )
        (language_model): Ministral3Model(
          (embed_tokens): Embedding(131072, 3072, padding_idx=11)
          (layers): ModuleList(
            (0-25): 26 x Ministral3DecoderLayer(
              (self_attn): Ministral3Attention(
                (q_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=3072, out_features=4096, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3072, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=4096, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=3072, out_features=1024, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3072, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=3072, out_features=1024, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3072, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=1024, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (o_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=4096, out_features=3072, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=4096, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=3072, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (mlp): Ministral3MLP(
                (gate_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=3072, out_features=9216, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3072, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=9216, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (up_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=3072, out_features=9216, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=3072, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=9216, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (down_proj): lora.Linear4bit(
                  (base_layer): Linear4bit(in_features=9216, out_features=3072, bias=False)
                  (lora_dropout): ModuleDict(
                    (default): Identity()
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=9216, out_features=16, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=16, out_features=3072, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (act_fn): SiLUActivation()
              )
              (input_layernorm): Ministral3RMSNorm((3072,), eps=1e-05)
              (post_attention_layernorm): Ministral3RMSNorm((3072,), eps=1e-05)
            )
          )
          (norm): Ministral3RMSNorm((3072,), eps=1e-05)
          (rotary_emb): Ministral3RotaryEmbedding()
        )
      )
      (lm_head): Linear(in_features=3072, out_features=131072, bias=False)
    )
  )
)

In [5]:
from src.prompts import get_inference_prompt_v5

eval_df["inference_prompt"] = eval_df["corrupted"].apply(get_inference_prompt_v5)
eval_df.iloc[0]["inference_prompt"]

'<s>[INST]Korrigiere die Grammatik im folgenden Text, aber behalte den ursprünglichen Stil und Ton bei. Verleihe dem Text keine formelle Note, wenn er diese nicht hat. Gib **nur** den korrigierten Satz zurück, ohne Anmerkungen. Wenn der Satz korrekt ist, gib ihn unverändert zurück.\n\nWir geht morgen auf zehn los.[/INST]'

In [6]:
# tokenize the list of prompts
tensors = tokenizer(None, eval_df["inference_prompt"].tolist(), return_tensors="pt", add_special_tokens=False, padding=True).to(model.device)
print(tensors["input_ids"].shape)

torch.Size([354, 102])

In [7]:
from tqdm import tqdm
corrections = []

# Generate corrections for each prompt in batch of 8
for i in tqdm(range(0, len(tensors["input_ids"]), 8), desc="Generating corrections"):
    batch = {key: val[i:i+8] for key, val in tensors.items()}
    output = model.generate(**batch, max_new_tokens=128)

    for j in range(output.shape[0]):
        # Decode only the NEW tokens (skip the input prompt tokens)
        input_length = batch["input_ids"].shape[1]
        generated_tokens = output[j][input_length:]
        output_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
        corrections.append(output_text)

Generating corrections: 100%|██████████| 45/45 [05:26<00:00,  7.26s/it]

In [8]:
corrections

['Wir gehen morgen um zehn los.',
 'Wie kannst du so einen Mann lieben?',
 'Ich kann faule Menschen nicht ausstehen.',
 'Manchmal fühle ich mich wie ein mutterloses Kind.',
 'Was genau muss er tun?',
 'So kann mich niemand erkennen.',
 'Ich will nicht, dass du mich falsch verstehst.',
 'Geht ihr oft ins Theater?',
 'Im Allgemeinen machen sie im Ausland Urlaub.',
 'Wir müssen unseren Vorfahren ehren.',
 'Ich frühstückte nicht, weil ich meistens zu spät aufstehe und ich keine Zeit mehr dafür habe.',
 'Ich glaube, sie geben zu viel für Kleider aus.',
 'Ich möchte dir nur daran erinnern, was du gestern gesagt hast.',
 'Unser Zug kommt morgen Mittag an.',
 'Ich mag Winter, weil ich viel Ski laufen, Schlitten fahren und Schlittschuh laufen kann.',
 'Glaubst du wirklich, dass ich dich verlassen will?',
 'Warum lässt sich ein altes Ehepaar scheiden?',
 'Jetzt kann ich Ihnen keine Antwort geben. Ich muss es mir nochmal überlegen.',
 'Er ist immer ungeduldig mit mir und er ist eifersüchtig auf meine Mutter.',
 'Das scheint wirklich keine weise Sache zu sein.',
 'Ich kann meinen Stiefvater nicht ausstehen.',
 'Ich hoffe, er antwortet sofort.',
 'Was würdest du dazu sagen, wenn wir in ein ungarisches Restaurant gehen würden?',
 'Du musst deine Halbschwestern helfen; du kannst nicht so eigensinnig sein.',
 'Ein guter Vater verbringt viel Zeit mit seinen Kindern.',
 'Ich konnte es nicht aushalten, ohne zu lachen, als er diese dumme Frage gestellt hat.',
 'Er hat sich anders überlegt; er will Barbara nicht heiraten.',
 'Da gibt es ein paar Probleme, die wir besprechen müssen.',
 'Ich habe jetzt keine Lust, Tennis zu spielen.',
 'Meine Schwiegermutter ist empfindlich gegenüber lauter Musik.',
 'Die Schüler haben keine Lust, zur Schule zu gehen.',
 'Entweder verlieben sie sich, oder sie schlafen ein.',
 'Was passiert, wenn sich alte Jungfrauen und Junggesellen in einer Party treffen?',
 'Mein Traum ist ein Mann, der mir treu sein kann.',
 'Er trifft nächste Woche seine Ex-Frau.',
 'Die Kusins spielen im Garten Ball, während die anderen draußen sind.',
 'Heutzutage sind die Menschen wild, frech, ungeduldig und egoistisch.',
 'Vergiss nicht, dass es leicht ist, Leute um Missverstehen, die wir nicht kennen.',
 'Eure Generation lebt schon in einer anderen Welt.',
 'Was soll ich sagen, ich auch nicht.',
 'Auf jeden Fall möchte ich neidische und eingebildete Menschen nicht kennenlernen und ich kann sie einfach nicht ausstehen.',
 'Ich wünsche, dass du recht hast!',
 'Ich denke, das ist eine großartige Idee.',
 'Mein Partner ist der aufopfernde Mensch, den ich je gekannt habe.',
 'Was würdest du dazu sagen, unsere Hochzeitsreise auf den Bahamas zu verbringen?',
 'Ich verstehe nicht, warum die jungen Leute Hard Rock so sehr mag und es ist so wild und zur gleichen Zeit ziemlich langweilig.',
 'Immer dieselben Akkorde, denselben Rhythmus, denselben Klang.',
 'Versucht nicht, Logik im Geschmack zu finden.',
 'Die Frage wird oft gestellt: Wer die wirkliche Mutter ist, diejenige, die das Kind gebärt, oder diejenige, die das Kind erzieht.',
 'Vielleicht sollte das Kind zuerst gefragt werden.',
 'Manchmal erziehen Menschen die Kinder von anderen Leuten und lieben sie so, als ob sie ihre eigenen wären.',
 'Vielleicht sollte die Frage gar nicht gestellt werden.',
 'Eine Antwort auf so eine Frage ist nie leicht.',
 'Flegel ist im Allgemeinen sehr empfindlich, manchmal auch frech und ungeduldig.',
 'Wann normalerweise ihr frühstücken?',
 'Trotzdem ist es aufregend um zu sehen, wie sie wachsen und schließlich erwachsene werden.',
 'Seitdem wir verheiratet sind, frühstückt wir so spät wie möglich.',
 'Ich glaube nicht, dass sie wissen, was sie tun.',
 'Du weißt nicht, worunter ich sprichst.',
 'Sage es einer, solange du nicht mehr darüber weiß.',
 'Arbeitet Sie immer noch für Audi?',
 'Der Bräutigam ist sehr stolz auf seine Braut.',
 'Was geht hier vor, Leute? Kann ich irgendwie helfen?',
 'Wir essen normalerweise kein Fleisch, aber in diesen Tagen essen wir viel Schinken, weil es Ostern ist.',
 'Unsere besten Freunde kommen über das Wochenende.',
 'Wir können die Arbeit bis sonntag nicht beenden, es sei denn, sie hilft uns.',
 'Seit der Scheidung ist sie sehr niedergeschlagen.',
 'Es ist einfach, sich in ein Mädchen wie sie zu verlieben.',
 'Ich besuche jeden Tag meine kranke Taufpatin.',
 'Störe ihn nicht, während er an einem neuen Buch arbeitet!',
 'Nach der Hochzeit fahren sie in Miami auf Hochzeitsreise.',
 'Er hört sich immer die morgennachrichten an, bevor er zur Arbeit geht.',
 'Ich bin wirklich nicht eifersüchtig auf sie, aber ich glaube, dass das schon zu viel ist.',
 'Sie hasst die billigen Waren.',
 'Sie geben immer mehr aus, als sie sollten.',
 'Kannst du deine Schule zeichnen?',
 'Er ist ein wohlbekannter Lehrer in der Stadt, hat ausgezeichnete Resultate und ist sehr stolz auf seine Schüler.',
 'Leider verstehe ich die Frage nicht genau. Würden Sie sie bitte wiederholen?',
 'Wir können ins Kino oder in ein elegantes Restaurant gehen – Entscheide du!',
 'Viele sagen, dass, wenn du wirklich große Probleme hast, es immer noch besser ist zu rufen und zu schreien, als niedergeschlagen zu sein.',
 'Verbringt wir den Abend zusammen!',
 'Ich glaube nicht, dass sie wissen, worüber sie sprechen.',
 'Wir haben eine wunderbare Hochzeitsreise!',
 'Wer es kann, der macht es, wer nicht, der lehrt es.',
 'Er möchte meine Pflegetochter verloben, und er arbeitet aber schon seit Monaten nicht.',
 'Wir wünschen euch eine glückliche Ehe!',
 'Sei nicht so niedergeschlagen; das Leben ist schön!',
 'Er ist jetzt 80 Jahre alt und möchte eine hübschere Witwe heiraten.',
 'Er ist 30 Jahre älter als sie, aber dieser Fakt stört die Dame nicht.',
 'Sein Vermögen ist doch davon nicht betroffen, oder?',
 'Ich liebe meine Frau und möchte mich nicht scheiden lassen. Auf keinen Fall!',
 'Eine wahre Freundschaft ist immer selbstlos.',
 'Wie rührend, dass du zu uns gekommen bist und uns diese Geschichte erzählst! Wir glauben dir nicht.',
 'Glück kann man nicht mit Geld kaufen.',
 'Sie hasst ihren Ex-Mann, weil er sie verlassen hat.',
 'Wie kann er sein eigenes Land verraten?',
 'Wer zuletzt lacht, lacht am besten.',
 'Du musst nicht flüstern. In diesem Zimmer können uns niemand hören.',
 'Er liebt seine Ex-Frau immer noch und würde ihr gern verzeihen, was sie ihm angetan hat.',
 'Lass mich sehen, wie hoch du springen kannst.',
 'Du musst sehr geduldig und aufopfernd sein, wenn du ein Kind erziehen willst.',
 'Manchmal können die Babys die ganze Nacht durch Weinen.',
 'Wenn du schwanger wirst, musst du zum Arzt gehen.',
 'Ich bin zu jung, ich will noch kein Kind zur Welt bringen.',
 'Sie vergnügen sich sehr gut, während wir wie die Pferde arbeiten.',
 'Wenn die Kinder aufwachsen, verlassen sie meistens ihr Elternhaus.',
 'Hast du keine Lust, auf einen Baum zu klettern?',
 'Spielt ihr nicht zweimal die Woche Tennis?',
 'Während Ihrer Schwangerschaft dürfen Sie nicht rauchen.',
 'Ich kann ihn nicht verzeihen, könntest du?',
 'Ich hasse es, früh aufzustehen, nicht du?',
 'Verbringt wir die Nacht zusammen!',
 'Wie kann man einen Freund so verraten?',
 'Er war mir wirklich untreu.',
 'Ich glaube, ich kann sie verstehen.',
 'Hier kommt der Bus, bitte alle einsteigen!',
 'Sie können es nicht aushalten, ohne ihn zu vergeben.',
 'Sie waren dir immer treu.',
 'Du hast keinen Grund, eifersüchtig auf ihn zu sein.',
 'Ich weiß nicht, was ich tun soll.',
 'Ich hasse es, ständig mit meinem Schwiegervater zu streiten.',
 'Wirklich? Haben sie die Einladung doch angenommen?',
 'Ich bin so froh, dass sie morgen den Abendessen kommen.',
 'Sie waren so müde, dass sie sich ausruhen mussten.',
 'Warum schaffst du es nicht, dein Geld auf die Bank zu bringen?',
 'Bleibt, wo ihr seid! Wir kommen gleich, um euch zu retten.',
 'Mein Schwager ist einer der wenigen Menschen, der vor niemandem Angst hat.',
 'Meine Kusine hat nicht zu viele Freunde, aber sie liebt sie alle sehr.',
 'Es wäre da viele sicherer.',
 'Die Nacht ist spannend und wartet auf kühne Männer.',
 'Nichts Besonderes. Hast du irgendeine gute Idee?',
 'Machtet ihr irgendetwas heute nacht?',
 'Es wird alles gut, das verspreche ich dir!',
 'Die Faulen und die Ungeschickten können zu Hause bleiben.',
 'Verstehe mich nicht falsch, wir wollen keinen Ärger.',
 'Das ist ein sehr neter Ort, ich kann es dir versichern.',
 'Weißt du, einmal die Woche treffen wir uns in einer alten Kneipe.',
 'Wir trinken Bier, Wein, sprechen über Politik und unterhalten uns über die guten alten Zeiten, als wir noch jung, frei und unverheiratet waren.',
 'Aber Frauen sehen diese Dinge wahrscheinlich anders.',
 'Erinnere du dich noch daran, wie viele Abenteuer wir zusammen erlebt haben? Das waren noch Zeiten!',
 'Nur wenige erinnern sich daran, dass es noch Zeiten gab, in denen Frauen die Männer geliebt hatten und nicht neidisch zu ihnen waren.',
 'Du musst auch dein Auto und dein Haus verkaufen.',
 'Nur, um ein paar Dinge zu erwähnen.',
 'Einst waren sie so nett, süß und zärtlich.',
 'Vielleicht sollten wir auf ihr hören, weil sie uns wahrscheinlich besser kennen als wir sie kennen.',
 'Schließlich bringen sie uns in die Welt und nicht andersrum.',
 'Und es könnte sein, dass sie recht haben und wir uns irren.',
 'Wir könnten uns öfter Gedanken über diese Kleinigkeit machen.',
 'Ich bin mir nicht sicher, dass er der richtige für diese Arbeit ist.',
 'Finde mir dann ein besseres!',
 'Geschäftsführender Direktor zu sein ist eine harte Arbeit mit großer Verantwortung.',
 'Ich glaube, du bietest zu wenig Geld an.',
 'Erinnere dich an den Spruch: Wenn du mit Bananen bezahlst, dann arbeiten nur Affen mit dir.',
 'Ich will, dass du weniger ausgibst.',
 'Wenn du so weitermachst, werden wir bald pleite gehen.',
 'Warum musst du immer die teuersten Kleider und Schuhe kaufen?',
 'Inzwischen haben wir schon alle unsere alten Freunde verloren.',
 'Glaubst du, dass ich ein Bankier bin?',
 'Keiner von ihnen kommt mehr zu uns, weil sie deinen Lebensstil nicht ertragen können.',
 'Ich glaube, wir haben sie endgültig verloren.',
 'Vor unserer Hochzeit habe ich nicht gedacht, dass du eines Tages so neidisch und eigensinnig sein wirst.',
 'Sie sagen, dass du eitel und eingebildet geworden bist.',
 'Ich schlage vor, dass wir uns so schnell wie möglich scheiden lassen.',
 'Wenn ich gewusst hätte, dass du dich so viel ändern würdest, hätte ich es mir noch rechtzeitig anders überlegt.',
 'Bei unserer Hochzeitsreise hast du gesagt, dass dir mein Geld nicht interessiert und du mich nur für mich selbst liebst.',
 'Du sagst, du willst keine Kinder gebären, weil die Geburt deiner Figur nicht gut tun würde.',
 'Wem würde ich mich jetzt streiten, wenn deine Mutter genau so gedacht hätte?',
 'Ich bedaure es fürchterlich, aber ich kann darüber nicht lachen.',
 'Vielleicht habe ich keinen Sinn für Humor.',
 'Das war die witzigste Geschichte, die ich je gehört habe.',
 'Warum sagst du mir das jetzt?',
 'Was für ein schöner Morgen!',
 'Dann ist es Zeit für das Großreinemachen im Frühling!',
 'Der Himmel ist blau, die Sonne scheint, die Vögel singen.',
 'Alles ist so grün im Garten, der Frühling ist da!',
 'Wer kann entscheiden, was verrückt und was normal ist?',
 'Versuche nicht, meine Stimmung zu verderben; es gelingt dir sowieso schon nicht!',
 'Das ist eine verrückte Idee, denkst du nicht?',
 'Keiner soll mir sagen, was ich mit meinem Leben anfangen soll.',
 'Entschuldige, ich habe es nicht so gemeint.',
 'Binst du mit mir einverstanden?',
 'Ich habe schon zu viele Ratschläge bekommen, ohne darum gebeten zu haben.',
 'Ich glaube, keiner hat das Recht, anderen zu sagen, was sie tun sollen.',
 'Ich denke, dass dies ein aufregendes Thema ist.',
 'Wechseln wir das Thema, denn es ist an der Zeit, über etwas anderes zu sprechen.',
 'Schau! Zurzeit spricht jeder über sich selbst und seine eigenen Probleme.',
 'Und wenn sie niemanden finden können, der ihnen zuhört, dann gehen sie zum Psychiater.',
 'Sie bezahlen ihn 100 Dollar pro Stunde und sind glücklich.',
 'Ich finde es ziemlich langweilig.',
 'Siehst du, so einfach ist das Leben.',
 'Warum soll ich diese langweilige Arbeit annehmen?',
 'Die Menschen können es nicht aushalten, ohne jeden ihrer kleinen seelischen Sorgen zu analysieren.',
 'Ich kann es nicht ausstehen, den ganzen Tag in einem langweiligen Büro zu arbeiten.',
 'Glaub nicht, dass es einfach sein wird; es gibt Tausende von Arbeitslosen.',
 'Ich kann bestimmt etwas Aufregenderes finden.',
 'Vergiss nicht, dass die meisten Leute eine Arbeit haben, die von neun bis fünf dauert.',
 'Ich werde es auf jeden Fall versuchen.',
 'Das kann gut sein. Für mich aber ist das Leben zu kurz, um einen Fehler zu begehen.',
 'Einverstanden! Aber trotzdem, wenn etwas schief läuft, dann kannst du dich auf mich verlassen.',
 'Dafür sind schließlich seine schließlich guten Freunde da!',
 'Das ist das, wovon wir leben.',
 'Das ist alles deine Schuld.',
 'Mein Gott, wir sind auf dem falschen Bus!',
 'Ich bringe dir immer dein Leibgericht und deine Lieblingszigarette ins Gefängnis.',
 'Lass mich dich daran erinnern, dass du auch ein menschliches Wesen bist, das sich irren kann.',
 'Warum wollen sie, dass wir alles in der Voraus bezahlen?',
 'Willst du, dass ich sie frage?',
 'Vielleicht glauben sie, dass uns das Geld ausgegangen ist.',
 'Das heißt also, dass uns jemand verraten haben muss.',
 'Keineswegs. Sie würden uns die Wahrheit sowieso nicht sagen.',
 'Die Welt ist wild geworden, und wir arbeiten wie die Pferde.',
 'Die Schwiegertochter interessierte sich nie für etwas.',
 'Wir müssen die Übersetzung bis Sonntagabend machen, sonst zahlen sie uns keinen Pfennig.',
 'Sie ist ungeduldig und eifersüchtig auf mich.',
 'Vielleicht verstehst du die Situation nur falsch.',
 'Bitte dein Sohn, mit ihr zu sprechen.',
 'Es besteht die Möglichkeit, dass sie Recht haben.',
 'Manchmal habe ich auch das Gefühl, dass du nicht wahrnehmen willst, dass dein Sohn erwachsen ist.',
 'Sie sagt immer, dass ich zulassen sollte, dass mein Sohn sein eigenes Leben lebt.',
 'Versuche zu verstehen, dass er erwachsen geworden ist und eine eigene Familie hat und du nicht mehr die wichtigste Person in seinem Leben bist.',
 'Aber ich kann es nicht aushalten, nicht den kleinen Jungen in ihm zu sehen, den ich allein erzogen habe.',
 'Ich glaube, dein Enkelkind, Luca, ist das neue Licht deiner Augen.',
 'Leider weiß ich wenig über das Thema.',
 'Du kannst nie sicher sein, ob dein Chef es ernst meint oder nicht.',
 'Bald zurück kommen sie, nicht wahr?',
 'Ich bin mir nicht mehr sicher.',
 'Hast du schlechte Erfahrungen gemacht?',
 'Wir spielen oft im Tennisklub.',
 'Sie kommen immer zu spät, und ich kann unpünktliche Menschen nicht ausstehen.',
 'Die Menschen halten ihre Versprechen nicht ein.',
 'Ich glaube, man kann niemand mehr vertrauen.',
 'Du müsstest geduldiger sein.',
 'An meiner Stelle wäre du auch böse.',
 'Leider können manche sich nie ändern.',
 'Was sagst du zu einem Bier?',
 'Ich glaube, die Lage könnte schlimmer sein.',
 'Wer interessiert sich schon, was er zu Hause macht?',
 'Dein Leben wird zur Hölle.',
 'Unsere Umgebung ist angenehm still.',
 'Verliebe dich nie in einem berühmten Menschen.',
 'Wir wollen nirgendwo hinziehen.',
 'Ich mache immer Yoga, wenn ich mich müde und niedergeschlagen fühle.',
 'Ein Wohnortswechsel ist nicht geplant.',
 'Sie ist so bescheiden, dass sie nie über sich selbst reden.',
 'Du rufst umsonst, denn hier hört dich niemand.',
 'Das war wirklich ein rührender Moment.',
 'Leider erfährt man es immer weniger zurzeit.',
 'Keine Angst, er kommt wieder in Ordnung.',
 'Es ist wunderbar, in einer glücklichen Familie aufzuwachsen.',
 'Wenn du ein neugeborenes Baby hast, musst du fast den ganzen Tag mit ihm verbringen.',
 'Es ist sehr schwierig mit einem Baby. Besonders, wenn es wenig schlafen und viel weint.',
 'Ich spüre, dass ich das nicht mehr aushalten kann.',
 'Ich wusste nicht, ob ich es erwähnen soll oder nicht.',
 'Wenn ich gewusst hätte, dass es so schwer werden würde, dann würde ich damit nicht anfangen.',
 'Die Zwillinge haben angefangen, in der Mitte der Küche Ball zu spielen.',
 'Unsere Situation ist nicht so einfach wie du denkst.',
 'Du müsstest das Tempo verlangsamen, denn du fährst zu schnell.',
 'Ihre Stiefmutter war alles andere als glücklich.',
 'Das ist unglaublich, aber wahr.',
 'Er hat seinen besten Freund verraten.',
 'Weißt du, wie man Brot zubereitet wird?',
 'Wenn du es nicht sagen würdest, würde ich es bestimmt nicht glauben.',
 'Sie sind in ganz Ungarn wohlbekannt.',
 'Erzähl mir von eurer Hochzeitsreise!',
 'Was könnte wichtig sein als Gesundheit?',
 'Ich nehme nichts an, habe aber Angst vor einer unangenehmen Überraschung.',
 'Er lernt schnell und vergisst schnell.',
 'Ist es nicht gefährlich, in wilden Bergflüssen zu rudern?',
 'Du fragst die falsche Person, ich hab es noch nie gemacht.',
 'Versprich solche Sachen nicht, die du später nicht erfüllen kannst!',
 'Sie hat mir diese wichtigen Neuigkeiten ins Ohr geflüstert.',
 'Und wenn das Wasser nicht nur tief, sondern auch kalt ist, dann sind deine Überlebenschancen gering, auch wenn du schwimmen kannst.',
 'Segeln kann auch gefährlich sein, denn du könntest in tiefes Wasser fallen.',
 'Es war wirklich eine angenehme Überraschung.',
 'Zuerst wollte ich es nicht glauben.',
 'Ich muss etwas missverstanden haben.',
 'Ich habe auch schlechte Nachrichten.',
 'Der Unfall war durch irgendeine Sorgfaltlosigkeit verursacht.',
 'Das Kind ist plötzlich ins Auto gesprungen und der Fahrer konnte nichts tun.',
 'Ja, so tun Sie es wenigstens einmal die Woche.',
 'Sonntagmorgen schläft selbst die Großstädte ruhig.',
 'Es wurde sofort ins Krankenhaus gebracht und fühlt sich jetzt schon gut.',
 'Ich hasse Großstädte. Die Menschen entfremden sich dort völlig voneinander.',
 'Ich glaube, wir müssen akzeptieren, dass die Menschen verschieden sind und verschiedene Lebensstile bevorzugen.',
 'Das ist meine Sache, wie viel ich für Kleidern ausbe.',
 'Du machst einen großen Fehler, wenn du glaubst, dass du jeden mit Geld kaufen kannst.',
 'Woraus sind diese Schuhe gemacht worden?',
 'Solange ich meine Rechnungen bezahle, bin ich der Boss.',
 'Das ist ein altes Bild von meiner Nichte, als sie noch lange Haare hatte.',
 'Warum kannst du meine Gründe nicht verstehen?',
 "Halt's Maul, das geht dir nichts an!",
 "Was gibt's heute Abend auf dem Fernsehen?",
 'Jazzmusiker müssen sehr gut gebildet sein.',
 'Welche Musik gefällt dir am meisten?',
 'Das ist einfach zu beantworten, denn Jazz ist meine Lieblingsmusik.',
 'Zwei Dinge braucht sie wirklich sehr: Freiheit und Fantasie.',
 'Sie müssen die meisten Lieder auswendig können und muss alle Akkorde in ihnen kennen.',
 'Ihre Bildung gibt ihnen Freiheit und ihr Talent gibt ihnen Fantasie.',
 'Anders könnten sie nicht frei improvisieren.',
 'Du kannst nicht gleichzeitig Baby und diese große Tasche tragen.',
 'Ich habe mal mit einem Musiklehrer gesprochen und er hat gesagt: Wenn ich nur talentiert genug wäre, könnte ich Jazz spielen.',
 'Ich fürchte, das ist das kleinste, was wir haben.',
 'Wenn ich es gewusst hätte, hätte ich es nicht gekauft.',
 'Warum ist das so unglaublich?',
 'Ich möchte es gegen ein Kleineres austauschen.',
 'Mein Schwiegersohn ist der großartigste Kerl, den ich je getroffen habe.',
 'Sag mir, bist du wirklich so verliebt in sie?',
 'Wenn ich mich recht erinnere, haben uns die Menschen genau das gleiche gesagt, als wir das Alter waren.',
 'Er ist ein typischer Flegel, freig für Erwachsene und ziemlich eingebildet.',
 'Sei wir genau! Wir sprechen natürlich über Eltern und ihre Kinder.',
 'Zeig mir eine Generation, die mit ihren Nachfahren zufrieden ist!',
 'Ich würde nicht zulassen, dass meine Tochter mit ihr ausgeht.',
 'Und nichts ist wichtiger als das.',
 'Und zeig mir eine Generation, die mit ihren Vorfahren zufrieden ist!',
 'Aber es gibt eine Sache, die wir nicht vergessen dürfen.',
 'Er geht nicht nach Hause, es sei denn, jemand bezahlt seine Fahrkarte.',

In [9]:
pd.DataFrame({
    "corrupted": eval_df["corrupted"],
    "model_corrected": corrections,
    "original": eval_df["original"],
}).to_json("../outputs/Text-Tune-Small-v9-on-eval-v10.jsonl", orient="records", lines=True, force_ascii=False)

In [30]:
asd = pd.read_json("../outputs/Text-Tune-Small-v9-on-eval-v9.jsonl-results.jsonl", lines=True)
asd["corrupted"] = eval_df["corrupted"]
# asd.to_json("../outputs/Text-Tune-Small-v9-on-eval-v9.jsonl-results-with-corrupted.jsonl", orient="records", lines=True, force_ascii=False)
asd.head()

,original,model_corrected,is_grammatically_correct,meaning_preserved,reason,corrupted
0,Ich kann faule Menschen nicht ausstehen.,Ich kann faule Menschen nicht ausstehen.,True,True,unchanged and correct,Ich können faule menschen nicht ausstehen.
1,Wie kannst du so einen Mann lieben?,Wie kannst du so einen Mann lieben?,True,True,unchanged and correct,Wie kann du so ein Mann lieben?
2,Wir gehen morgen um zehn los.,Wir gehen morgen um zehn los.,True,True,unchanged and correct,Wir geht morgen von zehn los.
3,So kann mich niemand erkennen.,So kann mich niemand erkennen.,True,True,unchanged and correct,So können mich niemand erkennen.
4,Manchmal fühle ich mich wie ein mutterloses Kind.,Manchmal fühle ich mich wie ein mutterloses Kind.,True,True,unchanged and correct,Manchmal fühle ich mich wie einen mutterlose K...

In [35]:
asd[asd["meaning_preserved"] == False].to_json("../outputs/Text-Tune-Small-v9-on-eval-v9-meaning_not_preserved.jsonl", orient="records", lines=True, force_ascii=False)